### ISSUE TITLE
Incorrect changelog type

### ISSUE THREAD

**Issue by zerebos** [SpoonMcForky/BetterDiscordPlugins#1]
See here in your changelog https://github.com/SpoonMcForky/BetterDiscordPlugins/blob/0d4a545c790cae213cddbe019dd8a81c75bf5d82/Plugins/KeyboardClick.plugin.js#L29

That is not a valid `type` value, please see the documentation https://rauenzi.github.io/BDPluginLibrary/docs/module-Modals-Changelog.html

**Comment by SpoonMcForky** [comment]
Fixed, thanks for pointing that out.
